// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: juristic.proto

package juristic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SovereignNode_RegisterAgent_FullMethodName     = "/rsj.v3.sovereign.SovereignNode/RegisterAgent"
	SovereignNode_SendHeartbeat_FullMethodName     = "/rsj.v3.sovereign.SovereignNode/SendHeartbeat"
	SovereignNode_UpdateStatus_FullMethodName      = "/rsj.v3.sovereign.SovereignNode/UpdateStatus"
	SovereignNode_DispatchDirective_FullMethodName = "/rsj.v3.sovereign.SovereignNode/DispatchDirective"
	SovereignNode_StreamLogs_FullMethodName        = "/rsj.v3.sovereign.SovereignNode/StreamLogs"
	SovereignNode_SyncState_FullMethodName         = "/rsj.v3.sovereign.SovereignNode/SyncState"
	SovereignNode_RetrieveContext_FullMethodName   = "/rsj.v3.sovereign.SovereignNode/RetrieveContext"
	SovereignNode_CommitState_FullMethodName       = "/rsj.v3.sovereign.SovereignNode/CommitState"
	SovereignNode_SendSecureMessage_FullMethodName = "/rsj.v3.sovereign.SovereignNode/SendSecureMessage"
	SovereignNode_PollInbox_FullMethodName         = "/rsj.v3.sovereign.SovereignNode/PollInbox"
	SovereignNode_SubmitEvidence_FullMethodName    = "/rsj.v3.sovereign.SovereignNode/SubmitEvidence"
)

// SovereignNodeClient is the client API for SovereignNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Definition
type SovereignNodeClient interface {
	// Agent Lifecycle
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*AgentProfile, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Directives (Command & Control)
	DispatchDirective(ctx context.Context, in *Directive, opts ...grpc.CallOption) (*DirectiveAck, error)
	StreamLogs(ctx context.Context, in *LogSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Memory & State
	SyncState(ctx context.Context, in *StateEntry, opts ...grpc.CallOption) (*StateAck, error)
	RetrieveContext(ctx context.Context, in *ContextQuery, opts ...grpc.CallOption) (*StateEntry, error)
	CommitState(ctx context.Context, in *CommitStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Inter-Link (Encrypted Comms)
	SendSecureMessage(ctx context.Context, in *EncryptedPacket, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PollInbox(ctx context.Context, in *InboxQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedPacket], error)
	// Worker Evidence (Merged from WorkerNode)
	SubmitEvidence(ctx context.Context, in *EvidencePacket, opts ...grpc.CallOption) (*WorkerResponse, error)
}

type sovereignNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewSovereignNodeClient(cc grpc.ClientConnInterface) SovereignNodeClient {
	return &sovereignNodeClient{cc}
}

func (c *sovereignNodeClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*AgentProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentProfile)
	err := c.cc.Invoke(ctx, SovereignNode_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, SovereignNode_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SovereignNode_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) DispatchDirective(ctx context.Context, in *Directive, opts ...grpc.CallOption) (*DirectiveAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectiveAck)
	err := c.cc.Invoke(ctx, SovereignNode_DispatchDirective_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) StreamLogs(ctx context.Context, in *LogSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SovereignNode_ServiceDesc.Streams[0], SovereignNode_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogSubscription, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SovereignNode_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *sovereignNodeClient) SyncState(ctx context.Context, in *StateEntry, opts ...grpc.CallOption) (*StateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateAck)
	err := c.cc.Invoke(ctx, SovereignNode_SyncState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) RetrieveContext(ctx context.Context, in *ContextQuery, opts ...grpc.CallOption) (*StateEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateEntry)
	err := c.cc.Invoke(ctx, SovereignNode_RetrieveContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) CommitState(ctx context.Context, in *CommitStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SovereignNode_CommitState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) SendSecureMessage(ctx context.Context, in *EncryptedPacket, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SovereignNode_SendSecureMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignNodeClient) PollInbox(ctx context.Context, in *InboxQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SovereignNode_ServiceDesc.Streams[1], SovereignNode_PollInbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InboxQuery, EncryptedPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SovereignNode_PollInboxClient = grpc.ServerStreamingClient[EncryptedPacket]

func (c *sovereignNodeClient) SubmitEvidence(ctx context.Context, in *EvidencePacket, opts ...grpc.CallOption) (*WorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerResponse)
	err := c.cc.Invoke(ctx, SovereignNode_SubmitEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SovereignNodeServer is the server API for SovereignNode service.
// All implementations must embed UnimplementedSovereignNodeServer
// for forward compatibility.
//
// Service Definition
type SovereignNodeServer interface {
	// Agent Lifecycle
	RegisterAgent(context.Context, *RegisterAgentRequest) (*AgentProfile, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*emptypb.Empty, error)
	// Directives (Command & Control)
	DispatchDirective(context.Context, *Directive) (*DirectiveAck, error)
	StreamLogs(*LogSubscription, grpc.ServerStreamingServer[LogEntry]) error
	// Memory & State
	SyncState(context.Context, *StateEntry) (*StateAck, error)
	RetrieveContext(context.Context, *ContextQuery) (*StateEntry, error)
	CommitState(context.Context, *CommitStateRequest) (*emptypb.Empty, error)
	// Inter-Link (Encrypted Comms)
	SendSecureMessage(context.Context, *EncryptedPacket) (*emptypb.Empty, error)
	PollInbox(*InboxQuery, grpc.ServerStreamingServer[EncryptedPacket]) error
	// Worker Evidence (Merged from WorkerNode)
	SubmitEvidence(context.Context, *EvidencePacket) (*WorkerResponse, error)
	mustEmbedUnimplementedSovereignNodeServer()
}

// UnimplementedSovereignNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSovereignNodeServer struct{}

func (UnimplementedSovereignNodeServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*AgentProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedSovereignNodeServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedSovereignNodeServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedSovereignNodeServer) DispatchDirective(context.Context, *Directive) (*DirectiveAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchDirective not implemented")
}
func (UnimplementedSovereignNodeServer) StreamLogs(*LogSubscription, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedSovereignNodeServer) SyncState(context.Context, *StateEntry) (*StateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedSovereignNodeServer) RetrieveContext(context.Context, *ContextQuery) (*StateEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveContext not implemented")
}
func (UnimplementedSovereignNodeServer) CommitState(context.Context, *CommitStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitState not implemented")
}
func (UnimplementedSovereignNodeServer) SendSecureMessage(context.Context, *EncryptedPacket) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSecureMessage not implemented")
}
func (UnimplementedSovereignNodeServer) PollInbox(*InboxQuery, grpc.ServerStreamingServer[EncryptedPacket]) error {
	return status.Error(codes.Unimplemented, "method PollInbox not implemented")
}
func (UnimplementedSovereignNodeServer) SubmitEvidence(context.Context, *EvidencePacket) (*WorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEvidence not implemented")
}
func (UnimplementedSovereignNodeServer) mustEmbedUnimplementedSovereignNodeServer() {}
func (UnimplementedSovereignNodeServer) testEmbeddedByValue()                       {}

// UnsafeSovereignNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SovereignNodeServer will
// result in compilation errors.
type UnsafeSovereignNodeServer interface {
	mustEmbedUnimplementedSovereignNodeServer()
}

func RegisterSovereignNodeServer(s grpc.ServiceRegistrar, srv SovereignNodeServer) {
	// If the following call panics, it indicates UnimplementedSovereignNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SovereignNode_ServiceDesc, srv)
}

func _SovereignNode_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_DispatchDirective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Directive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).DispatchDirective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_DispatchDirective_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).DispatchDirective(ctx, req.(*Directive))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SovereignNodeServer).StreamLogs(m, &grpc.GenericServerStream[LogSubscription, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SovereignNode_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _SovereignNode_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_SyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).SyncState(ctx, req.(*StateEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_RetrieveContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).RetrieveContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_RetrieveContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).RetrieveContext(ctx, req.(*ContextQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_CommitState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).CommitState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_CommitState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).CommitState(ctx, req.(*CommitStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_SendSecureMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptedPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).SendSecureMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_SendSecureMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).SendSecureMessage(ctx, req.(*EncryptedPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignNode_PollInbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InboxQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SovereignNodeServer).PollInbox(m, &grpc.GenericServerStream[InboxQuery, EncryptedPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SovereignNode_PollInboxServer = grpc.ServerStreamingServer[EncryptedPacket]

func _SovereignNode_SubmitEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidencePacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignNodeServer).SubmitEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignNode_SubmitEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignNodeServer).SubmitEvidence(ctx, req.(*EvidencePacket))
	}
	return interceptor(ctx, in, info, handler)
}

// SovereignNode_ServiceDesc is the grpc.ServiceDesc for SovereignNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SovereignNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rsj.v3.sovereign.SovereignNode",
	HandlerType: (*SovereignNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _SovereignNode_RegisterAgent_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _SovereignNode_SendHeartbeat_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _SovereignNode_UpdateStatus_Handler,
		},
		{
			MethodName: "DispatchDirective",
			Handler:    _SovereignNode_DispatchDirective_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _SovereignNode_SyncState_Handler,
		},
		{
			MethodName: "RetrieveContext",
			Handler:    _SovereignNode_RetrieveContext_Handler,
		},
		{
			MethodName: "CommitState",
			Handler:    _SovereignNode_CommitState_Handler,
		},
		{
			MethodName: "SendSecureMessage",
			Handler:    _SovereignNode_SendSecureMessage_Handler,
		},
		{
			MethodName: "SubmitEvidence",
			Handler:    _SovereignNode_SubmitEvidence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _SovereignNode_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PollInbox",
			Handler:       _SovereignNode_PollInbox_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "juristic.proto",
}
