// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rsj.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The data structure for the evidence packet
type EvidencePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	RawData       string                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidencePacket) Reset() {
	*x = EvidencePacket{}
	mi := &file_rsj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePacket) ProtoMessage() {}

func (x *EvidencePacket) ProtoReflect() protoreflect.Message {
	mi := &file_rsj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePacket.ProtoReflect.Descriptor instead.
func (*EvidencePacket) Descriptor() ([]byte, []int) {
	return file_rsj_proto_rawDescGZIP(), []int{0}
}

func (x *EvidencePacket) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EvidencePacket) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *EvidencePacket) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// The response from the worker node
type WorkerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessingTimeMs int32                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkerResponse) Reset() {
	*x = WorkerResponse{}
	mi := &file_rsj_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResponse) ProtoMessage() {}

func (x *WorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsj_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResponse.ProtoReflect.Descriptor instead.
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return file_rsj_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkerResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_rsj_proto protoreflect.FileDescriptor

const file_rsj_proto_rawDesc = "" +
	"\n" +
	"\trsj.proto\x12\x03rsj\"]\n" +
	"\x0eEvidencePacket\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\tR\arawData\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"p\n" +
	"\x0eWorkerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x05R\x10processingTimeMs2H\n" +
	"\n" +
	"WorkerNode\x12:\n" +
	"\x0eSubmitEvidence\x12\x13.rsj.EvidencePacket\x1a\x13.rsj.WorkerResponseB\x1cZ\x1arsj-v3-monorepo/pkg/workerb\x06proto3"

var (
	file_rsj_proto_rawDescOnce sync.Once
	file_rsj_proto_rawDescData []byte
)

func file_rsj_proto_rawDescGZIP() []byte {
	file_rsj_proto_rawDescOnce.Do(func() {
		file_rsj_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rsj_proto_rawDesc), len(file_rsj_proto_rawDesc)))
	})
	return file_rsj_proto_rawDescData
}

var file_rsj_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rsj_proto_goTypes = []any{
	(*EvidencePacket)(nil), // 0: rsj.EvidencePacket
	(*WorkerResponse)(nil), // 1: rsj.WorkerResponse
}
var file_rsj_proto_depIdxs = []int32{
	0, // 0: rsj.WorkerNode.SubmitEvidence:input_type -> rsj.EvidencePacket
	1, // 1: rsj.WorkerNode.SubmitEvidence:output_type -> rsj.WorkerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rsj_proto_init() }
func file_rsj_proto_init() {
	if File_rsj_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rsj_proto_rawDesc), len(file_rsj_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rsj_proto_goTypes,
		DependencyIndexes: file_rsj_proto_depIdxs,
		MessageInfos:      file_rsj_proto_msgTypes,
	}.Build()
	File_rsj_proto = out.File
	file_rsj_proto_goTypes = nil
	file_rsj_proto_depIdxs = nil
}
