// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: rsj.proto

package worker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerNode_SubmitEvidence_FullMethodName = "/rsj.WorkerNode/SubmitEvidence"
)

// WorkerNodeClient is the client API for WorkerNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Service Definition
type WorkerNodeClient interface {
	SubmitEvidence(ctx context.Context, in *EvidencePacket, opts ...grpc.CallOption) (*WorkerResponse, error)
}

type workerNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerNodeClient(cc grpc.ClientConnInterface) WorkerNodeClient {
	return &workerNodeClient{cc}
}

func (c *workerNodeClient) SubmitEvidence(ctx context.Context, in *EvidencePacket, opts ...grpc.CallOption) (*WorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerResponse)
	err := c.cc.Invoke(ctx, WorkerNode_SubmitEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerNodeServer is the server API for WorkerNode service.
// All implementations must embed UnimplementedWorkerNodeServer
// for forward compatibility.
//
// The Service Definition
type WorkerNodeServer interface {
	SubmitEvidence(context.Context, *EvidencePacket) (*WorkerResponse, error)
	mustEmbedUnimplementedWorkerNodeServer()
}

// UnimplementedWorkerNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerNodeServer struct{}

func (UnimplementedWorkerNodeServer) SubmitEvidence(context.Context, *EvidencePacket) (*WorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEvidence not implemented")
}
func (UnimplementedWorkerNodeServer) mustEmbedUnimplementedWorkerNodeServer() {}
func (UnimplementedWorkerNodeServer) testEmbeddedByValue()                    {}

// UnsafeWorkerNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerNodeServer will
// result in compilation errors.
type UnsafeWorkerNodeServer interface {
	mustEmbedUnimplementedWorkerNodeServer()
}

func RegisterWorkerNodeServer(s grpc.ServiceRegistrar, srv WorkerNodeServer) {
	// If the following call panics, it indicates UnimplementedWorkerNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerNode_ServiceDesc, srv)
}

func _WorkerNode_SubmitEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidencePacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServer).SubmitEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNode_SubmitEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServer).SubmitEvidence(ctx, req.(*EvidencePacket))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerNode_ServiceDesc is the grpc.ServiceDesc for WorkerNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rsj.WorkerNode",
	HandlerType: (*WorkerNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvidence",
			Handler:    _WorkerNode_SubmitEvidence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsj.proto",
}
