// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: juristic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState int32

const (
	AgentState_STATE_UNKNOWN    AgentState = 0
	AgentState_STATE_IDLE       AgentState = 1
	AgentState_STATE_PROCESSING AgentState = 2
	AgentState_STATE_ERROR      AgentState = 3
	AgentState_STATE_OFFLINE    AgentState = 4
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_IDLE",
		2: "STATE_PROCESSING",
		3: "STATE_ERROR",
		4: "STATE_OFFLINE",
	}
	AgentState_value = map[string]int32{
		"STATE_UNKNOWN":    0,
		"STATE_IDLE":       1,
		"STATE_PROCESSING": 2,
		"STATE_ERROR":      3,
		"STATE_OFFLINE":    4,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_juristic_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_juristic_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{0}
}

type AccessLevel int32

const (
	AccessLevel_ACCESS_READ  AccessLevel = 0
	AccessLevel_ACCESS_WRITE AccessLevel = 1
	AccessLevel_ACCESS_ADMIN AccessLevel = 2
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_READ",
		1: "ACCESS_WRITE",
		2: "ACCESS_ADMIN",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_READ":  0,
		"ACCESS_WRITE": 1,
		"ACCESS_ADMIN": 2,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_juristic_proto_enumTypes[1].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_juristic_proto_enumTypes[1]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{1}
}

type CommitStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      string                 `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStateRequest) Reset() {
	*x = CommitStateRequest{}
	mi := &file_juristic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStateRequest) ProtoMessage() {}

func (x *CommitStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStateRequest.ProtoReflect.Descriptor instead.
func (*CommitStateRequest) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{0}
}

func (x *CommitStateRequest) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *CommitStateRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

type AgentProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SovereignLevel int32                  `protobuf:"varint,2,opt,name=sovereign_level,json=sovereignLevel,proto3" json:"sovereign_level,omitempty"` // Rank in the hierarchy
	ParentAgentId  string                 `protobuf:"bytes,3,opt,name=parent_agent_id,json=parentAgentId,proto3" json:"parent_agent_id,omitempty"`
	Capabilities   []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	CurrentState   AgentState             `protobuf:"varint,5,opt,name=current_state,json=currentState,proto3,enum=rsj.v3.sovereign.AgentState" json:"current_state,omitempty"`
	JoinedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentProfile) Reset() {
	*x = AgentProfile{}
	mi := &file_juristic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProfile) ProtoMessage() {}

func (x *AgentProfile) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProfile.ProtoReflect.Descriptor instead.
func (*AgentProfile) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{1}
}

func (x *AgentProfile) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentProfile) GetSovereignLevel() int32 {
	if x != nil {
		return x.SovereignLevel
	}
	return 0
}

func (x *AgentProfile) GetParentAgentId() string {
	if x != nil {
		return x.ParentAgentId
	}
	return ""
}

func (x *AgentProfile) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentProfile) GetCurrentState() AgentState {
	if x != nil {
		return x.CurrentState
	}
	return AgentState_STATE_UNKNOWN
}

func (x *AgentProfile) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type RegisterAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SovereignLevel int32                  `protobuf:"varint,2,opt,name=sovereign_level,json=sovereignLevel,proto3" json:"sovereign_level,omitempty"`
	Capabilities   []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_juristic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetSovereignLevel() int32 {
	if x != nil {
		return x.SovereignLevel
	}
	return 0
}

func (x *RegisterAgentRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LoadAverage   float32                `protobuf:"fixed32,2,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_juristic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetLoadAverage() float32 {
	if x != nil {
		return x.LoadAverage
	}
	return 0
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged      bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	PendingDirectives bool                   `protobuf:"varint,2,opt,name=pending_directives,json=pendingDirectives,proto3" json:"pending_directives,omitempty"` // Signal if agent needs to pull work
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_juristic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetPendingDirectives() bool {
	if x != nil {
		return x.PendingDirectives
	}
	return false
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NewState      AgentState             `protobuf:"varint,2,opt,name=new_state,json=newState,proto3,enum=rsj.v3.sovereign.AgentState" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_juristic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateStatusRequest) GetNewState() AgentState {
	if x != nil {
		return x.NewState
	}
	return AgentState_STATE_UNKNOWN
}

type Directive struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId      string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`
	SourceAgentId    string                 `protobuf:"bytes,2,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	TargetAgentId    string                 `protobuf:"bytes,3,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	Priority         int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                                        // 0 = Low, 100 = Critical
	ExecutionContext *structpb.Struct       `protobuf:"bytes,5,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"` // Flexible JSON payload
	TimeoutMs        int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Directive) Reset() {
	*x = Directive{}
	mi := &file_juristic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directive) ProtoMessage() {}

func (x *Directive) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directive.ProtoReflect.Descriptor instead.
func (*Directive) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{6}
}

func (x *Directive) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *Directive) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *Directive) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *Directive) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Directive) GetExecutionContext() *structpb.Struct {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

func (x *Directive) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Directive) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DirectiveAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId   string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveAck) Reset() {
	*x = DirectiveAck{}
	mi := &file_juristic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveAck) ProtoMessage() {}

func (x *DirectiveAck) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveAck.ProtoReflect.Descriptor instead.
func (*DirectiveAck) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{7}
}

func (x *DirectiveAck) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *DirectiveAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DirectiveAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogSubscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetDirectiveId string                 `protobuf:"bytes,1,opt,name=target_directive_id,json=targetDirectiveId,proto3" json:"target_directive_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogSubscription) Reset() {
	*x = LogSubscription{}
	mi := &file_juristic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSubscription) ProtoMessage() {}

func (x *LogSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSubscription.ProtoReflect.Descriptor instead.
func (*LogSubscription) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{8}
}

func (x *LogSubscription) GetTargetDirectiveId() string {
	if x != nil {
		return x.TargetDirectiveId
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_juristic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Raw bytes for maximum flexibility
	OwnerAgentId  string                 `protobuf:"bytes,3,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,4,opt,name=access_level,json=accessLevel,proto3,enum=rsj.v3.sovereign.AccessLevel" json:"access_level,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEntry) Reset() {
	*x = StateEntry{}
	mi := &file_juristic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEntry) ProtoMessage() {}

func (x *StateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEntry.ProtoReflect.Descriptor instead.
func (*StateEntry) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{10}
}

func (x *StateEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StateEntry) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *StateEntry) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_READ
}

func (x *StateEntry) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type StateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateAck) Reset() {
	*x = StateAck{}
	mi := &file_juristic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAck) ProtoMessage() {}

func (x *StateAck) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAck.ProtoReflect.Descriptor instead.
func (*StateAck) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{11}
}

func (x *StateAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StateAck) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ContextQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestorAgentId string                 `protobuf:"bytes,2,opt,name=requestor_agent_id,json=requestorAgentId,proto3" json:"requestor_agent_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContextQuery) Reset() {
	*x = ContextQuery{}
	mi := &file_juristic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextQuery) ProtoMessage() {}

func (x *ContextQuery) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextQuery.ProtoReflect.Descriptor instead.
func (*ContextQuery) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{12}
}

func (x *ContextQuery) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContextQuery) GetRequestorAgentId() string {
	if x != nil {
		return x.RequestorAgentId
	}
	return ""
}

type EncryptedPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecipientId      string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	SenderId         string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	Signature        string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Verification signature
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedPacket) Reset() {
	*x = EncryptedPacket{}
	mi := &file_juristic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPacket) ProtoMessage() {}

func (x *EncryptedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPacket.ProtoReflect.Descriptor instead.
func (*EncryptedPacket) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{13}
}

func (x *EncryptedPacket) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *EncryptedPacket) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EncryptedPacket) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *EncryptedPacket) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type InboxQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FetchAll      bool                   `protobuf:"varint,2,opt,name=fetch_all,json=fetchAll,proto3" json:"fetch_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxQuery) Reset() {
	*x = InboxQuery{}
	mi := &file_juristic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxQuery) ProtoMessage() {}

func (x *InboxQuery) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxQuery.ProtoReflect.Descriptor instead.
func (*InboxQuery) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{14}
}

func (x *InboxQuery) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InboxQuery) GetFetchAll() bool {
	if x != nil {
		return x.FetchAll
	}
	return false
}

type EvidencePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	RawData       string                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidencePacket) Reset() {
	*x = EvidencePacket{}
	mi := &file_juristic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePacket) ProtoMessage() {}

func (x *EvidencePacket) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePacket.ProtoReflect.Descriptor instead.
func (*EvidencePacket) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{15}
}

func (x *EvidencePacket) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EvidencePacket) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *EvidencePacket) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type WorkerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessingTimeMs int32                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkerResponse) Reset() {
	*x = WorkerResponse{}
	mi := &file_juristic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResponse) ProtoMessage() {}

func (x *WorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResponse.ProtoReflect.Descriptor instead.
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{16}
}

func (x *WorkerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkerResponse) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_juristic_proto protoreflect.FileDescriptor

const file_juristic_proto_rawDesc = "" +
	"\n" +
	"\x0ejuristic.proto\x12\x10rsj.v3.sovereign\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"T\n" +
	"\x12CommitStateRequest\x12\x1b\n" +
	"\tnew_state\x18\x01 \x01(\tR\bnewState\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\"\x9a\x02\n" +
	"\fAgentProfile\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fsovereign_level\x18\x02 \x01(\x05R\x0esovereignLevel\x12&\n" +
	"\x0fparent_agent_id\x18\x03 \x01(\tR\rparentAgentId\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12A\n" +
	"\rcurrent_state\x18\x05 \x01(\x0e2\x1c.rsj.v3.sovereign.AgentStateR\fcurrentState\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"~\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fsovereign_level\x18\x02 \x01(\x05R\x0esovereignLevel\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"w\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fload_average\x18\x02 \x01(\x02R\vloadAverage\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"f\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12-\n" +
	"\x12pending_directives\x18\x02 \x01(\bR\x11pendingDirectives\"k\n" +
	"\x13UpdateStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\tnew_state\x18\x02 \x01(\x0e2\x1c.rsj.v3.sovereign.AgentStateR\bnewState\"\xba\x02\n" +
	"\tDirective\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12&\n" +
	"\x0fsource_agent_id\x18\x02 \x01(\tR\rsourceAgentId\x12&\n" +
	"\x0ftarget_agent_id\x18\x03 \x01(\tR\rtargetAgentId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12D\n" +
	"\x11execution_context\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x10executionContext\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\fDirectiveAck\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"A\n" +
	"\x0fLogSubscription\x12.\n" +
	"\x13target_directive_id\x18\x01 \x01(\tR\x11targetDirectiveId\"{\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xdb\x01\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12$\n" +
	"\x0eowner_agent_id\x18\x03 \x01(\tR\fownerAgentId\x12@\n" +
	"\faccess_level\x18\x04 \x01(\x0e2\x1d.rsj.v3.sovereign.AccessLevelR\vaccessLevel\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"@\n" +
	"\bStateAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"N\n" +
	"\fContextQuery\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x12requestor_agent_id\x18\x02 \x01(\tR\x10requestorAgentId\"\x9c\x01\n" +
	"\x0fEncryptedPacket\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"D\n" +
	"\n" +
	"InboxQuery\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tfetch_all\x18\x02 \x01(\bR\bfetchAll\"]\n" +
	"\x0eEvidencePacket\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\tR\arawData\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"p\n" +
	"\x0eWorkerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x05R\x10processingTimeMs*i\n" +
	"\n" +
	"AgentState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x14\n" +
	"\x10STATE_PROCESSING\x10\x02\x12\x0f\n" +
	"\vSTATE_ERROR\x10\x03\x12\x11\n" +
	"\rSTATE_OFFLINE\x10\x04*B\n" +
	"\vAccessLevel\x12\x0f\n" +
	"\vACCESS_READ\x10\x00\x12\x10\n" +
	"\fACCESS_WRITE\x10\x01\x12\x10\n" +
	"\fACCESS_ADMIN\x10\x022\x8d\a\n" +
	"\rSovereignNode\x12W\n" +
	"\rRegisterAgent\x12&.rsj.v3.sovereign.RegisterAgentRequest\x1a\x1e.rsj.v3.sovereign.AgentProfile\x12X\n" +
	"\rSendHeartbeat\x12\".rsj.v3.sovereign.HeartbeatRequest\x1a#.rsj.v3.sovereign.HeartbeatResponse\x12M\n" +
	"\fUpdateStatus\x12%.rsj.v3.sovereign.UpdateStatusRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11DispatchDirective\x12\x1b.rsj.v3.sovereign.Directive\x1a\x1e.rsj.v3.sovereign.DirectiveAck\x12M\n" +
	"\n" +
	"StreamLogs\x12!.rsj.v3.sovereign.LogSubscription\x1a\x1a.rsj.v3.sovereign.LogEntry0\x01\x12E\n" +
	"\tSyncState\x12\x1c.rsj.v3.sovereign.StateEntry\x1a\x1a.rsj.v3.sovereign.StateAck\x12O\n" +
	"\x0fRetrieveContext\x12\x1e.rsj.v3.sovereign.ContextQuery\x1a\x1c.rsj.v3.sovereign.StateEntry\x12K\n" +
	"\vCommitState\x12$.rsj.v3.sovereign.CommitStateRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x11SendSecureMessage\x12!.rsj.v3.sovereign.EncryptedPacket\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\tPollInbox\x12\x1c.rsj.v3.sovereign.InboxQuery\x1a!.rsj.v3.sovereign.EncryptedPacket0\x01\x12T\n" +
	"\x0eSubmitEvidence\x12 .rsj.v3.sovereign.EvidencePacket\x1a .rsj.v3.sovereign.WorkerResponseB\tZ\a./protob\x06proto3"

var (
	file_juristic_proto_rawDescOnce sync.Once
	file_juristic_proto_rawDescData []byte
)

func file_juristic_proto_rawDescGZIP() []byte {
	file_juristic_proto_rawDescOnce.Do(func() {
		file_juristic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_juristic_proto_rawDesc), len(file_juristic_proto_rawDesc)))
	})
	return file_juristic_proto_rawDescData
}

var file_juristic_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_juristic_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_juristic_proto_goTypes = []any{
	(AgentState)(0),               // 0: rsj.v3.sovereign.AgentState
	(AccessLevel)(0),              // 1: rsj.v3.sovereign.AccessLevel
	(*CommitStateRequest)(nil),    // 2: rsj.v3.sovereign.CommitStateRequest
	(*AgentProfile)(nil),          // 3: rsj.v3.sovereign.AgentProfile
	(*RegisterAgentRequest)(nil),  // 4: rsj.v3.sovereign.RegisterAgentRequest
	(*HeartbeatRequest)(nil),      // 5: rsj.v3.sovereign.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: rsj.v3.sovereign.HeartbeatResponse
	(*UpdateStatusRequest)(nil),   // 7: rsj.v3.sovereign.UpdateStatusRequest
	(*Directive)(nil),             // 8: rsj.v3.sovereign.Directive
	(*DirectiveAck)(nil),          // 9: rsj.v3.sovereign.DirectiveAck
	(*LogSubscription)(nil),       // 10: rsj.v3.sovereign.LogSubscription
	(*LogEntry)(nil),              // 11: rsj.v3.sovereign.LogEntry
	(*StateEntry)(nil),            // 12: rsj.v3.sovereign.StateEntry
	(*StateAck)(nil),              // 13: rsj.v3.sovereign.StateAck
	(*ContextQuery)(nil),          // 14: rsj.v3.sovereign.ContextQuery
	(*EncryptedPacket)(nil),       // 15: rsj.v3.sovereign.EncryptedPacket
	(*InboxQuery)(nil),            // 16: rsj.v3.sovereign.InboxQuery
	(*EvidencePacket)(nil),        // 17: rsj.v3.sovereign.EvidencePacket
	(*WorkerResponse)(nil),        // 18: rsj.v3.sovereign.WorkerResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 20: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 21: google.protobuf.Empty
}
var file_juristic_proto_depIdxs = []int32{
	0,  // 0: rsj.v3.sovereign.AgentProfile.current_state:type_name -> rsj.v3.sovereign.AgentState
	19, // 1: rsj.v3.sovereign.AgentProfile.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 2: rsj.v3.sovereign.UpdateStatusRequest.new_state:type_name -> rsj.v3.sovereign.AgentState
	20, // 3: rsj.v3.sovereign.Directive.execution_context:type_name -> google.protobuf.Struct
	19, // 4: rsj.v3.sovereign.Directive.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: rsj.v3.sovereign.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 6: rsj.v3.sovereign.StateEntry.access_level:type_name -> rsj.v3.sovereign.AccessLevel
	19, // 7: rsj.v3.sovereign.StateEntry.last_updated:type_name -> google.protobuf.Timestamp
	4,  // 8: rsj.v3.sovereign.SovereignNode.RegisterAgent:input_type -> rsj.v3.sovereign.RegisterAgentRequest
	5,  // 9: rsj.v3.sovereign.SovereignNode.SendHeartbeat:input_type -> rsj.v3.sovereign.HeartbeatRequest
	7,  // 10: rsj.v3.sovereign.SovereignNode.UpdateStatus:input_type -> rsj.v3.sovereign.UpdateStatusRequest
	8,  // 11: rsj.v3.sovereign.SovereignNode.DispatchDirective:input_type -> rsj.v3.sovereign.Directive
	10, // 12: rsj.v3.sovereign.SovereignNode.StreamLogs:input_type -> rsj.v3.sovereign.LogSubscription
	12, // 13: rsj.v3.sovereign.SovereignNode.SyncState:input_type -> rsj.v3.sovereign.StateEntry
	14, // 14: rsj.v3.sovereign.SovereignNode.RetrieveContext:input_type -> rsj.v3.sovereign.ContextQuery
	2,  // 15: rsj.v3.sovereign.SovereignNode.CommitState:input_type -> rsj.v3.sovereign.CommitStateRequest
	15, // 16: rsj.v3.sovereign.SovereignNode.SendSecureMessage:input_type -> rsj.v3.sovereign.EncryptedPacket
	16, // 17: rsj.v3.sovereign.SovereignNode.PollInbox:input_type -> rsj.v3.sovereign.InboxQuery
	17, // 18: rsj.v3.sovereign.SovereignNode.SubmitEvidence:input_type -> rsj.v3.sovereign.EvidencePacket
	3,  // 19: rsj.v3.sovereign.SovereignNode.RegisterAgent:output_type -> rsj.v3.sovereign.AgentProfile
	6,  // 20: rsj.v3.sovereign.SovereignNode.SendHeartbeat:output_type -> rsj.v3.sovereign.HeartbeatResponse
	21, // 21: rsj.v3.sovereign.SovereignNode.UpdateStatus:output_type -> google.protobuf.Empty
	9,  // 22: rsj.v3.sovereign.SovereignNode.DispatchDirective:output_type -> rsj.v3.sovereign.DirectiveAck
	11, // 23: rsj.v3.sovereign.SovereignNode.StreamLogs:output_type -> rsj.v3.sovereign.LogEntry
	13, // 24: rsj.v3.sovereign.SovereignNode.SyncState:output_type -> rsj.v3.sovereign.StateAck
	12, // 25: rsj.v3.sovereign.SovereignNode.RetrieveContext:output_type -> rsj.v3.sovereign.StateEntry
	21, // 26: rsj.v3.sovereign.SovereignNode.CommitState:output_type -> google.protobuf.Empty
	21, // 27: rsj.v3.sovereign.SovereignNode.SendSecureMessage:output_type -> google.protobuf.Empty
	15, // 28: rsj.v3.sovereign.SovereignNode.PollInbox:output_type -> rsj.v3.sovereign.EncryptedPacket
	18, // 29: rsj.v3.sovereign.SovereignNode.SubmitEvidence:output_type -> rsj.v3.sovereign.WorkerResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_juristic_proto_init() }
func file_juristic_proto_init() {
	if File_juristic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_juristic_proto_rawDesc), len(file_juristic_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_juristic_proto_goTypes,
		DependencyIndexes: file_juristic_proto_depIdxs,
		EnumInfos:         file_juristic_proto_enumTypes,
		MessageInfos:      file_juristic_proto_msgTypes,
	}.Build()
	File_juristic_proto = out.File
	file_juristic_proto_goTypes = nil
	file_juristic_proto_depIdxs = nil
}
