// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: juristic.proto

package juristic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseRef       string                 `protobuf:"bytes,1,opt,name=case_ref,json=caseRef,proto3" json:"case_ref,omitempty"`
	Doctrine      string                 `protobuf:"bytes,2,opt,name=doctrine,proto3" json:"doctrine,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_juristic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{0}
}

func (x *StateRequest) GetCaseRef() string {
	if x != nil {
		return x.CaseRef
	}
	return ""
}

func (x *StateRequest) GetDoctrine() string {
	if x != nil {
		return x.Doctrine
	}
	return ""
}

func (x *StateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_juristic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_juristic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_juristic_proto_rawDescGZIP(), []int{1}
}

func (x *StateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_juristic_proto protoreflect.FileDescriptor

const file_juristic_proto_rawDesc = "" +
	"\n" +
	"\x0ejuristic.proto\x12\vjuristic.v1\"]\n" +
	"\fStateRequest\x12\x19\n" +
	"\bcase_ref\x18\x01 \x01(\tR\acaseRef\x12\x1a\n" +
	"\bdoctrine\x18\x02 \x01(\tR\bdoctrine\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"A\n" +
	"\rStateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2W\n" +
	"\x0fJuristicService\x12D\n" +
	"\vCommitState\x12\x19.juristic.v1.StateRequest\x1a\x1a.juristic.v1.StateResponseB\fZ\n" +
	"./juristicb\x06proto3"

var (
	file_juristic_proto_rawDescOnce sync.Once
	file_juristic_proto_rawDescData []byte
)

func file_juristic_proto_rawDescGZIP() []byte {
	file_juristic_proto_rawDescOnce.Do(func() {
		file_juristic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_juristic_proto_rawDesc), len(file_juristic_proto_rawDesc)))
	})
	return file_juristic_proto_rawDescData
}

var file_juristic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_juristic_proto_goTypes = []any{
	(*StateRequest)(nil),  // 0: juristic.v1.StateRequest
	(*StateResponse)(nil), // 1: juristic.v1.StateResponse
}
var file_juristic_proto_depIdxs = []int32{
	0, // 0: juristic.v1.JuristicService.CommitState:input_type -> juristic.v1.StateRequest
	1, // 1: juristic.v1.JuristicService.CommitState:output_type -> juristic.v1.StateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_juristic_proto_init() }
func file_juristic_proto_init() {
	if File_juristic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_juristic_proto_rawDesc), len(file_juristic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_juristic_proto_goTypes,
		DependencyIndexes: file_juristic_proto_depIdxs,
		MessageInfos:      file_juristic_proto_msgTypes,
	}.Build()
	File_juristic_proto = out.File
	file_juristic_proto_goTypes = nil
	file_juristic_proto_depIdxs = nil
}
