// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: juristic.proto

package juristic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JuristicService_CommitState_FullMethodName = "/juristic.v1.JuristicService/CommitState"
)

// JuristicServiceClient is the client API for JuristicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JuristicServiceClient interface {
	CommitState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
}

type juristicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJuristicServiceClient(cc grpc.ClientConnInterface) JuristicServiceClient {
	return &juristicServiceClient{cc}
}

func (c *juristicServiceClient) CommitState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, JuristicService_CommitState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JuristicServiceServer is the server API for JuristicService service.
// All implementations must embed UnimplementedJuristicServiceServer
// for forward compatibility.
type JuristicServiceServer interface {
	CommitState(context.Context, *StateRequest) (*StateResponse, error)
	mustEmbedUnimplementedJuristicServiceServer()
}

// UnimplementedJuristicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJuristicServiceServer struct{}

func (UnimplementedJuristicServiceServer) CommitState(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitState not implemented")
}
func (UnimplementedJuristicServiceServer) mustEmbedUnimplementedJuristicServiceServer() {}
func (UnimplementedJuristicServiceServer) testEmbeddedByValue()                         {}

// UnsafeJuristicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JuristicServiceServer will
// result in compilation errors.
type UnsafeJuristicServiceServer interface {
	mustEmbedUnimplementedJuristicServiceServer()
}

func RegisterJuristicServiceServer(s grpc.ServiceRegistrar, srv JuristicServiceServer) {
	// If the following call panics, it indicates UnimplementedJuristicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JuristicService_ServiceDesc, srv)
}

func _JuristicService_CommitState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JuristicServiceServer).CommitState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JuristicService_CommitState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JuristicServiceServer).CommitState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JuristicService_ServiceDesc is the grpc.ServiceDesc for JuristicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JuristicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "juristic.v1.JuristicService",
	HandlerType: (*JuristicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitState",
			Handler:    _JuristicService_CommitState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juristic.proto",
}
